# set base image (host OS)
FROM python:3.8

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN buck build ${HOME}/rascode/rascally/www:server
COPY ${HOME}/rascode/buck-out/gen/rascally/www/server.pex .

# copy the content of the local src directory to the working directory
COPY src/ .

# command to run on container start
CMD [ "python3", "./server.pex" ]
