python_binary(
    name = "spcli",
    main = "spcli.py",
    base_module = "smarthome",
    deps = [
        "//third-party/python/pyhs100:pyhs100",
    ],
    visibility = [
        "PUBLIC",
    ],
)
