# python_library(
#     name = ""
#     srcs = [],
#     deps = [],
#     visibility = [],
# )

python_binary(
    name = "spcli",
    main = "spcli.py",
    base_module = "smarthome",
    deps = [],
    visibility = [
        "PUBLIC",
    ],
)
