http_file(
    name = "typing-download",
    urls = [
        "https://files.pythonhosted.org/packages/3b/c0/e44213fcb799eac02881e2485724ba5b0914600bc9df6ed922e364fdc059/typing-3.7.4.3-py2-none-any.whl",
    ],
    sha256 = "283d868f5071ab9ad873e5e52268d611e851c870a2ba354193026f2dfb29d8b5",
    out = "typing-3.7.4.3-py2-none-any.whl",
)

prebuilt_python_library(
    name = "typing",
    binary_src = ":typing-download",
    deps = [],
    visibility = [
        "PUBLIC",
    ]
)
